version: '3.9'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  app:
    image: 'account:latest'
    build:
      context: .
    container_name: account
    ports:
      - 9090:8080